### ISSUE TITLE
netlify 빌드 커맨드 관련

### ISSUE THREAD

**Issue by mozodev** [team-durumi/wwm#2]
https://github.com/team-durumi/wwm/blob/645491dfe466e431754f5e86d1bb8f54be8eef01/netlify.toml#L3

몰랐는데 설정 파일에 빌드 커맨드 넣어놓으면 UI에서 수정해도 무시하고 그냥 그걸 쓰네요.

huod mod tidy
https://gohugo.io/commands/hugo_mod_tidy/
사용하지 않는 모듈을 삭제, 단정하게 한다.

hugo mod get -u ./...
https://gohugo.io/commands/hugo_mod_get/
Install the latest versions of all module dependencies:
hugo mod get -u
hugo mod get -u ./... (recursive)

모듈이 업데이트되지 않아서 https://github.com/team-durumi/theme-wwm/issues/24 이런 현상이 벌어지는 듯 ㅎ

**Comment by mozodev** [comment]
빌드 로그 중 모듈 업데이트
https://app.netlify.com/sites/women-war-museum/deploys/61d2515edae8f30008ce6806#L58-L66

경고: https://github.com/team-durumi/theme-wwm/blob/main/README.md#env 관련
https://app.netlify.com/sites/women-war-museum/deploys/61d2515edae8f30008ce6806#L68

이렇게 빌드가 잘 될 줄 알았으나... 똑같음 ㅋ

@woonjjang [git-blame]
https://github.com/team-durumi/wwm/commit/17b53e40a59eaf4b308c7f8c6b41f243563d6f29#diff-7d9962da7d9aa8db205659f7224a23edc3fdc78be5925db7951c0b45ba6a9b98

https://github.com/team-durumi/theme-wwm/blob/84c09cd6264e2bbb7b91c32e83d3f67be58d2f69/exampleSite/config/_default/module.yml#L5-L9

https://github.com/team-durumi/hugo-search-fuse-js-aa
이 모듈이 없어서 그랬...

**Comment by mozodev** [comment]
분명 이렇게까지 하는건 떠먹여주는게 맞는거 같아서... 어차피 이렇게 해도 체험이나 이해가 안되겠죠? ㅋ
이런 이슈는 화요일에 만나서 한 명이 운전대 잡고 같이 돌파해보는걸로 ㅎ
어떤 영화에서 왜 너네 미국애들은 항상 나라를 배에 비유하냐는 대사가 상당히 공감이 되어... 
난 미국을 별로 안 좋아하니까... 차에 비유하는걸로 ㅎ

**Comment by woonjjang** [comment]
네네 local에서 해당 모듈을 찍어놓고 https://github.com/team-durumi/hugo-search-fuse-js-aa 테스트는 했었는데, 저도 확인하고 배포하려고 반영은 안 하고 있었습니다. 

https://github.com/team-durumi/theme-wwm/issues/10 환경변수 같이 넘기는 부분은 운전대 잡고 같이 해 보고 싶습니다.
